### ISSUE TITLE
quiz ending early 

### ISSUE THREAD

**Issue by WilsontheWolf** [theusaf/kahoot-session#3] opened 2019-12-31 20:53 UTC
using the quiz [`3f27e4e3-410d-4bc6-9588-01392ef4d741`](https://create.kahoot.it/details/3f27e4e3-410d-4bc6-9588-01392ef4d741 )which is valid and public, the bot has weird actions upon joining. It fires the quiz ended event right away. This cause the user to not have an info variable making players look like this:
```js
[ { name: 'Test', id: '1662769797' } ]
```
This causes issues with consistancy.  I joined using `kahoot.js-updated` when the quiz starts it sometimes detects the quiz. I'll do some more testing.

**Comment by WilsontheWolf** [comment] 2019-12-31 21:00
it appears the error is actually in your code and not mine. heres the stack trace 
```js
TypeError: Cannot read property 'totalScore' of undefined
    at newHandler.endQuiz (/rbd/pnpm-volume/7168b0be-4467-427e-a706-060208f530c6/node_modules/.registry.npmjs.org/kahoot-session/1.5.1/node_modules/kahoot-session/WSHandler.js:1035:46)
    at newHandler.nextQuestion (/rbd/pnpm-volume/7168b0be-4467-427e-a706-060208f530c6/node_modules/.registry.npmjs.org/kahoot-session/1.5.1/node_modules/kahoot-session/WSHandler.js:951:10)
    at Timeout.setTimeout [as _onTimeout] (/rbd/pnpm-volume/7168b0be-4467-427e-a706-060208f530c6/node_modules/.registry.npmjs.org/kahoot-session/1.5.1/node_modules/kahoot-session/WSHandler.js:42:14)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by theusaf** [comment] 2020-01-10 21:38
Hmm, thanks for the report. I'll take a look at it.

**Comment by theusaf** [comment] 2020-01-10 21:44
Looks like the issue is on lines 950-954
```js
...
nextQuestion(isFirst,me){
    var me = me ? me : this;
    me.questionIndex++;
    if(me.questionIndex >= me.quiz.questions.length){
      me.endQuiz();
      return;
    }
    if(isFirst){me.questionIndex--;}
    me.emit("questionStart",me.quiz.questions[me.questionIndex]);
    let answerMap = {};
    let ans = [];
...
```
The `if(isFirst)` statement should come before the end quiz if statement to prevent quizzes from ending immediately on 1 question quizzes. I'll have an update soon.

**Comment by theusaf** [comment] 2020-01-10 21:48
Fixed in https://github.com/theusaf/kahoot-session/commit/b94996311b6df9174f7099e6ab032314087190a0 (1.5.2)

**Closed by theusaf** 2020-01-10 21:48 UTC
Labels: bug
